import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        cvc: {
          page: 'var(--cvc-page)',
          'page-elevated': 'var(--cvc-page-elevated)',
          'section-alt': 'var(--cvc-section-alt)',
          'image-overlay': 'var(--cvc-image-overlay)',
          card: 'var(--cvc-card)',
          'card-muted': 'var(--cvc-card-muted)',
          'card-deep': 'var(--cvc-card-deep)',
          'card-inner': 'var(--cvc-card-inner)',
          tile: 'var(--cvc-tile)',
          border: 'var(--cvc-border)',
          'border-muted': 'var(--cvc-border-muted)',
          'border-strong': 'var(--cvc-border-strong)',
          fg: 'var(--cvc-fg)',
          'fg-muted': 'var(--cvc-fg-muted)',
          'fg-subtle': 'var(--cvc-fg-subtle)',
          'fg-on-light': 'var(--cvc-fg-on-light)',
          nav: 'var(--cvc-nav)',
          'nav-border': 'var(--cvc-nav-border)',
          'hero-shade': 'var(--cvc-hero-shade)',
          'hero-fg': 'var(--cvc-hero-fg)',
          'hero-fg-muted': 'var(--cvc-hero-fg-muted)',
          'hero-pillars': 'var(--cvc-hero-pillars)',
          'hero-pillars-border': 'var(--cvc-hero-pillars-border)',
          'hero-pillars-divide': 'var(--cvc-hero-pillars-divide)',
          'hero-accent': 'var(--cvc-hero-accent)',
          navlink: 'var(--cvc-navlink-bg)',
          'navlink-border': 'var(--cvc-navlink-border)',
          hover: 'var(--cvc-hover)',
          'hover-strong': 'var(--cvc-hover-strong)',
          'audio-bar': 'var(--cvc-audio-bar)',
          'glass-panel': 'var(--cvc-glass-panel)',
          'section-title': 'var(--cvc-section-title)',
          'cta-fill': 'var(--cvc-cta-fill)',
        },
        'patriotic-red': '#CE2029',
        'patriotic-blue': '#3C3B6E',
        'patriotic-green': '#4A5D23',
        'patriotic-navy': '#1E3A5F',
        'patriotic-gold': '#FFD700',
      },
      fontFamily: {
        'display': ['Georgia', 'serif'],
        'sans': ['Inter', 'system-ui', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-patriotic': 'linear-gradient(135deg, #1E3A5F 0%, #3C3B6E 50%, #B22234 100%)',
        'stars-pattern': "url(\"data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.05'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E\")",
      },
    },
  },
  plugins: [],
}
export default config
